apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhishek67parmar/argo-app.git
    targetRevision: HEAD
    path: app-config
  destination:
    server: https://kubernetes.default.svc
    namespace: my-argo-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true
       
