apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agro-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhishek67parmar/argo-app/tree/main
    targetRevision: HEAD
    path: app-config
  destination:
    server: https://kubernetes.default.svc
    namespce: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true
       