apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: argo-app
  name: argo-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argo-app
status:
  loadBalancer: {}
